name: Test
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Run tests on ${{matrix.os}}, Godot ${{matrix.godot}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        godot: [4.4.0, 4.5.0, 4.6.0]
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{matrix.godot}}
          use-dotnet: false
          include-templates: true

      - name: Run tests
        run: |
          godot --headless --import
          godot --headless --script tests/run_tests.gd
