#!/usr/bin/env bash

SCRIPT_DIR=$(dirname -- "$( readlink -f -- "$0"; )";)
LOG="$SCRIPT_DIR/butler.log"

echo "Log file: $LOG"

case $1 in
    "--help")
        echo "Your happy little itch.io helper"
        exit 0
        ;;

    "push")
        SOURCE="$2"
        TARGET="$3"
        echo "SUCCESS: Push called, source=$SOURCE, target=$TARGET" | tee -a "$LOG"
        exit 0
        ;;

    *)
        echo "FAIL: Invalid arguments: $*" | tee -a "$LOG"
        exit 100
        ;;
esac
